### ISSUE TITLE
to use 'K' (upper case) as PyType when exposing x64 pointers (objects and void*)

### ISSUE THREAD

**Issue by pepcots** [cross-platform/ecs-python#1]
When exposing objects from a x64 exe, the PyType used is 'k' (lower case). It should be using 'K' upper case in order to store the address properly. The same issue when using void* parameters from an x64 application.

**Comment by MarcusTomlinson** [comment]
Thanks for this! This project definitely needs some love. I’ll try have a look at it over the weekend. A few unit tests and CI on x86 and x64 will be good too!

**Comment by MarcusTomlinson** [comment]
All fixed up @pepcots! Thank you for your help!

**Comment by pepcots** [comment]
Amazing work @MarcusTomlinson !! Many thanks!
